CC=gcc
CFLAGS= -g

%.o: %.c
	$(CC) $(CFLAGS) $< -c

linked-list: linked-list.c
factorial: factorial.c
hello: hello.c
loop: loop.c
merge-sort: merge-sort.c
binary-search: binary-search.c


.PHONY: clean
clean:
	-rm *.o



